### ISSUE TITLE
Failing Netlify Builds

### ISSUE THREAD

**Issue by richnoah** [w3c/wai-aria-practices#142] opened 2022-06-27 23:58 UTC
In the process of attempting to resolve the issue of missing content from [PR 2379](https://github.com/w3c/aria-practices/pull/2379) Bocoup and other contributors have encountered build errors on Netlify.
 
An example of the build error can be seen on this [deploy log](https://app.netlify.com/sites/wai-aria-practices2/deploys/62b9de8c7d5e6d00080a40c9). 
 
It appears there is a Netlify mismatch.  We found a similar issue on the Netlify build image repo [PR 790](https://github.com/netlify/build-image/pull/790)

**Comment by SteveALee** [comment] 2022-06-28 06:40
The most likely cause is a local build by someone has used a version on bundler that is not available in the netlify builds or clashes with that compatible with the Ruby version we use 2.6

This get recorded in the lock file.

It might be a problem with the bundler version not being fixed for local builds. If that is possible. Probably by making sure the lock file is under version control.

To resolve it make sure Ruby 2.6 is used locally and use a version of bundler specified in older lock files. The lock file should be checked in to vc to ensure local builds throw the error rather than netlify.

**Comment by SteveALee** [comment] 2022-06-28 14:54
Now I'm on my workstation I can clearly see the rror does not make sense

```
5:45:16 PM: Using bundler version 2.3.4 from Gemfile.lock
5:45:17 PM: ERROR:  Error installing bundler:
5:45:17 PM: 	"bundler" from bundler conflicts with /opt/buildhome/.rvm/gems/ruby-2.6.2/bin/bundler
```

I'm using bundler 2-3-10 and have had no problems. maybe they have changed they config?

**Comment by richnoah** [comment] 2022-06-28 14:55
@SteveALee who is they?

**Comment by evmiguel** [comment] 2022-06-28 15:18
@SteveALee thank you for deploying. Could you clear the cache for #138? It would be good to see the builds pass as well. Thank you!

**Comment by evmiguel** [comment] 2022-06-28 15:56
@SteveALee in addition to #138, could the caches for #140 and #141 be cleared as well?

**Comment by evmiguel** [comment] 2022-06-28 16:11
Thank you @SteveALee

**Comment by evmiguel** [comment] 2022-06-28 21:37
Hi @SteveALee, I pushed a new commit to #138, and the build is still failing. Also failing for #145, which is in draft right now. Could you clear the caches for these?

**Comment by richnoah** [comment] 2022-06-28 21:48
@SteveALee you mentioned having the ability to do this via the Netlify web app.  Are there credentials available for that in case we need to carry that out in the future?  Sorry to be pinging you so much in the wee hours.

**Comment by SteveALee** [comment] 2022-06-29 06:34
Best to get to the bottom of the problem as this should not keep happening. I suspect the bundler version recorded in the lock file.

I'll discuss with @shawna-slh the option to give someone team access to netlify but we have limited to avoid accidents.

**Comment by SteveALee** [comment] 2022-06-29 06:44
OK so changing the bundler version seems to make no difference. And only a no cache build works.

Seems it needs chasing with netlify

**Comment by SteveALee** [comment] 2022-06-29 06:46
Do you not see these button on the deploy log page?

![image](https://user-images.githubusercontent.com/618922/176369850-900c3b6e-f143-41eb-aef0-701a03194cf4.png)

**Comment by SteveALee** [comment] 2022-06-29 06:47
If you point me to the Netlify forum post you created I'll add more info

**Comment by richnoah** [comment] 2022-06-29 13:14
@SteveALee the Netifly forum post I referenced earlier was found through research.  It has since been removed.  We have not created a post in the forum but if it will help I am more than happy to do so.

**Comment by SteveALee** [comment] 2022-06-29 13:22
@richnoah ah, I see. no worries. I have a little time to explore today.

Did these previews ever deploy? If so any ideas as to what might have changed?

**Comment by SteveALee** [comment] 2022-06-29 13:47
I cannot see anything obvious that might cause the error - which is anyway not very specific. The config is good and comparable to others repos. As it only some new PRs that are failing it seem even less likely to be something Netlify specific. 

I suggest you raise an issue with Netlify in their forums.

**Comment by captn3m0** [comment] 2022-06-29 14:28
Facing the same issue with [endoflife.date builds](https://app.netlify.com/sites/endoflife-date/deploys/62bad0e3add131000ac00919) and I think the issue only exists for existing caches. Since Netlify doesn't provide a way to clear all build caches - only workaround for now seems to be to re-trigger a build.

**Comment by captn3m0** [comment] 2022-06-29 14:43
Filed #146 which avoids the issue by upgrading ruby to 2.7 (2.6 is no longer supported), which avoids the existing caches on Netlify.

Merging this should resolve the issue, however existing PRs will need to be rebased.

**Comment by evmiguel** [comment] 2022-06-29 14:50
@captn3m0 thank you for moving so quickly! I added a .ruby-version to #138 before seeing the above.

**Comment by SteveALee** [comment] 2022-06-29 15:00
In theory when I built without the cache that should have reset the issue by regenerating the cache- sigh! There is obviously a bug being triggered only in your repo as others are fine

Yes 2.6 is out of date but having you build your repo using a different version that the main wai website build may well lead to weird problems when @shawna-slh merges your code in.  That could invalidate your preview testing.

Upgrading everything to 2.7 woulds require a LOT of testing so we have not yet done it.

As a work around you could set that in your own branches but YOU MUST make sure to keep to 2.6 when we merging - that is a risk. I'll defer to @shawna-slh on that decision.

Also the ruby version that Netlify uses is defined in the netlify.toml file. So no need for a new file unless that takes precedence and makes you rollback  easier

**Comment by evmiguel** [comment] 2022-06-29 15:16
@SteveALee thank you for the clarification. I've removed the .ruby-version in #147 to be in congruence with WAI.

**Comment by evmiguel** [comment] 2022-06-29 20:09
@SteveALee could you please clear the cache for #148 in the meantime?

**Comment by SteveALee** [comment] 2022-06-29 20:29
deploy in progress.

**Comment by SteveALee** [comment] 2022-06-29 21:01
I tried a few things and switching the Docker image to be the Xenial Ubuntu my have fixed it. Absolutely no idea why

**Comment by evmiguel** [comment] 2022-06-29 21:31
Confirmed that build passes in #149 @richnoah @SteveALee

**Comment by SteveALee** [comment] 2022-06-30 08:24
yay - I [updated the support request](https://answers.netlify.com/t/deploy-fails-non-zero-exit-code-on-bundler-install/70245/4?u=slim) - it's still not been looked at by Netlify :(

**Closed** 2022-07-06 23:00 UTC
